# Site settings
title: Jorge's stuff
description: Jorge's stuff
author: jorgeper

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
header_pages: []  # Removes header navigation
author_show: false  # Removes author from footer
title: false  # Removes title
site_title: false  # Removes site title
footer: false  # Removes footer

# URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol, e.g. http://example.com

# Social media
github_username: jorgeper
# twitter_username: your-twitter-username
# linkedin_username: your-linkedin-username

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
